### ISSUE TITLE
Throwing exceptions doesn't work

### ISSUE THREAD

**Issue by tmszdmsk** [PayU-Tech/Ratel#3]
When there is an exception thrown from "discovered" service (exception is Exception subclass and is declared in API), java.lang.reflect.UndeclaredThrowableException is thrown instead. Without Ratel, it works as expected.

Excerpt from logs:
```
Processing of HessianServiceExporter remote call resulted in fatal exception: some.java.package.ServiceInterface.method: java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy46.get(Unknown Source)
...
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) [:1.7.0_45]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_45]
at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_45]
at com.payu.ratel.proxy.UnicastingInvocationHandler.invoke(UnicastingInvocationHandler.java:40) [ratel-core-1.0.0.jar:]
```

I will provide more sophisticated use case later (in form of integration test probably)

**Comment by lukaszPulawski** [comment]
Thx for input, waiting for the test.
