### ISSUE TITLE
Ratel doesn't fully support spring 3.2.x on client side (RESOLVED)

### ISSUE THREAD

**Issue by cannehal** [PayU-Tech/Ratel#40]
When client tries to connect to service we get following exception:

Caused by: java.lang.NoSuchMethodError: org.springframework.remoting.caucho.HessianProxyFactoryBean.setConnectTimeout(J)V
        at com.payu.ratel.client.ClientProxyDecorator.createServiceClientProxy(ClientProxyDecorator.java:46)
        at com.payu.ratel.client.zookeeper.ZookeeperProxyGenerator.generate(ZookeeperProxyGenerator.java:30)
        at com.payu.ratel.proxy.UnicastingInvocationHandler.invoke(UnicastingInvocationHandler.java:53)
(...)
org.jboss.ejb3.interceptors.aop.InvocationContextInterceptor$InvocationContext.proceed(InvocationContextInterceptor.java:138)
        ... 75 more
Caused by: java.lang.NoSuchMethodError: org.springframework.remoting.caucho.HessianProxyFactoryBean.setConnectTimeout(J)V
        at com.payu.ratel.client.ClientProxyDecorator.createServiceClientProxy(ClientProxyDecorator.java:46)
        at com.payu.ratel.client.zookeeper.ZookeeperProxyGenerator.generate(ZookeeperProxyGenerator.java:30)

Ratel should have an option to detect spring version and prepare client with timeout configuration (for spring 4.x) or without (for spring 3.2.x).

**Comment by lukaszPulawski** [comment]
Fix available in branch bugfix-40
